spring.application.name=harvest
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.rebdpjjwdoewdnigfbmq
spring.datasource.password=Harvest_19952026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

# logging.level.org.springframework.security=DEBUG
# logging.level.org.springframework.web=DEBUG

server.port=${PORT:9090}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=diafbadreddine11@gmail.com
spring.mail.password=pxvlmaabrlkzqtqv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

google.client.id=654804259696-7p6gkipvjf741mphqrbkucmq4omt9uj0.apps.googleusercontent.com
google.client.secret=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

app.email.from=comharvest32026@gmail.com
app.email.name=Harvest 3

# Twitter OAuth 2.0 Configuration
spring.security.oauth2.client.registration.twitter.client-id=SXZEREwxWkdkVEJSVmRvOEVpbzU6MTpjaQ
spring.security.oauth2.client.registration.twitter.client-secret=uzaqa6i1M8Sh5N-1FN7khvJ-N4OQljfaDeRUHoqsZ-oD7lDzv9
spring.security.oauth2.client.registration.twitter.redirect-uri={baseUrl}/login/oauth2/code/twitter
spring.security.oauth2.client.registration.twitter.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.twitter.scope=tweet.read,users.read,offline.access

spring.security.oauth2.client.provider.twitter.authorization-uri=https://twitter.com/i/oauth2/authorize
spring.security.oauth2.client.provider.twitter.token-uri=https://api.twitter.com/2/oauth2/token
spring.security.oauth2.client.provider.twitter.user-info-uri=https://api.twitter.com/2/users/me?user.fields=id,name,username,profile_image_url
spring.security.oauth2.client.provider.twitter.user-name-attribute=id

spring.security.oauth2.client.registration.discord.client-id=1469497359191769293
spring.security.oauth2.client.registration.discord.client-secret=IgeNFPBo7b_s-hwW92odiY6yvmzvIvUN
spring.security.oauth2.client.registration.discord.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.discord.redirect-uri={baseUrl}/login/oauth2/code/discord
spring.security.oauth2.client.registration.discord.client-name=Discord
spring.security.oauth2.client.registration.discord.scope=identify,email

spring.security.oauth2.client.provider.discord.authorization-uri=https://discord.com/api/oauth2/authorize
spring.security.oauth2.client.provider.discord.token-uri=https://discord.com/api/oauth2/token
spring.security.oauth2.client.provider.discord.user-info-uri=https://discord.com/api/users/@me
spring.security.oauth2.client.provider.discord.user-name-attribute=id


# logging.level.org.springframework.security.oauth2=TRACE
